import { Camera, MapPin, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  { icon: Camera, label: 'Report Issues', color: 'bg-[#e3f5f1]' },
  { icon: MapPin, label: 'Auto Location', color: 'bg-[#fff2d9]' },
  { icon: Zap, label: 'Faster Resolution', color: 'bg-[#e9edff]' }
];

export function AuthDecor() {
  return <section className="relative hidden min-h-screen overflow-hidden bg-[#eaf8f4] px-10 py-9 md:flex md:w-[55%] md:flex-col lg:px-16"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2.5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#0D7A6E] text-white"><MapPin size={21} fill="currentColor" /></span><span className="text-xl font-bold tracking-[-0.04em] text-[#0F2A2E]">InfraFix</span></div><p className="mt-1.5 pl-12 text-[9px] font-medium uppercase tracking-[0.11em] text-[#6a8583]">Solutions for your Infrastructure</p></div><Link to="/signup" className="text-sm font-semibold text-[#4f716e] hover:text-[#0D7A6E]">Don&apos;t have an Account? <span className="text-[#0D7A6E]">Sign up</span></Link></div><div className="relative z-10 mt-24 max-w-xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.22em] text-[#0D7A6E]">Together, we can</p><h1 className="max-w-lg text-5xl font-bold leading-[1.06] tracking-[-0.055em] text-[#0F2A2E] lg:text-6xl">Report Today for a <span className="text-[#0D7A6E]">Better Tomorrow</span></h1><p className="mt-6 max-w-md text-base leading-7 text-[#64817e]">Be a part of the change. Report infrastructure issues in your neighborhood and help build a cleaner, safer city.</p><div className="mt-9 flex flex-wrap gap-5">{features.map(({ icon: Icon, label, color }) => <div key={label} className="flex items-center gap-2.5 text-xs font-semibold text-[#466764]"><span className={`flex h-10 w-10 items-center justify-center rounded-full ${color} text-[#0D7A6E}`}><Icon size={18} /></span>{label}</div>)}</div></div><div className="absolute bottom-0 left-0 right-0 h-[37%] overflow-hidden" aria-hidden="true"><div className="absolute bottom-[-35%] left-[-5%] h-44 w-[110%] rounded-[50%] bg-[#a6ddd1]" /><div className="absolute bottom-[-5%] left-[-5%] h-28 w-[110%] rounded-[50%] bg-[#79c9ba] opacity-70" /><div className="absolute bottom-[32%] left-[18%] h-3 w-[70%] rotate-[-3deg] rounded-full bg-[#c4ebe2] opacity-70" /></div></section>;
}
